[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_functions = test_*

markers =
    unit: DB/Redis ke bina chalne wale fast tests
    integration: test database + fake redis wale tests

addopts = -v --tb=short