"""archived: original auto migration e3946014ab0b

This file is an archived copy of the autogenerated migration which attempted to
change primary key column types. It is kept for reference and was removed from
active migrations.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3946014ab0b'
down_revision: Union[str, Sequence[str], None] = '9d1b3f2a4c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Original autogenerated migration (archived)."""
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.alter_column('categories', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_unique_constraint(None, 'categories', ['slug'])
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('categories', 'description')
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.alter_column('products', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('products', 'slug',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint(op.f('products_name_key'), 'products', type_='unique')
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('products', 'stock')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))


def downgrade() -> None:
    """Downgrade for archived migration (not used)."""
    pass

