"""feat: complete checkout pricing, address and transaction schema

Revision ID: 2184aae0d905
Revises: 39b372e9eb51
Create Date: 2026-04-25 19:53:08.625184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2184aae0d905'
down_revision: Union[str, Sequence[str], None] = '39b372e9eb51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('house_no', sa.String(length=255), nullable=False),
    sa.Column('area', sa.String(length=255), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=255), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_order_id'), 'transaction', ['order_id'], unique=False)
    op.create_index(op.f('ix_transaction_razorpay_order_id'), 'transaction', ['razorpay_order_id'], unique=False)
    op.add_column('orders', sa.Column('address_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('subtotal_price', sa.Numeric(precision=10, scale=2), nullable=False,server_default='0.00' ))
    op.add_column('orders', sa.Column('tax_price', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.00'))
    op.add_column('orders', sa.Column('shipping_price', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.00'))
    op.add_column('orders', sa.Column('shipping_address_snapshot', sa.String(), nullable=True))
    op.create_foreign_key(None, 'orders', 'addresses', ['address_id'], ['id'], ondelete='SET NULL')
    op.drop_column('orders', 'shipping_address')
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'phone_number')
    op.add_column('orders', sa.Column('shipping_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'shipping_address_snapshot')
    op.drop_column('orders', 'shipping_price')
    op.drop_column('orders', 'tax_price')
    op.drop_column('orders', 'subtotal_price')
    op.drop_column('orders', 'address_id')
    op.drop_index(op.f('ix_transaction_razorpay_order_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_order_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
