"""add composite indexes on products and orders

Revision ID: 815be9c1e7ce
Revises: 304e2b7061fc
Create Date: 2026-07-12 10:30:22.162144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815be9c1e7ce'
down_revision: Union[str, Sequence[str], None] = '304e2b7061fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_user_status_created', 'orders', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_products_category_price', 'products', ['category_id', 'price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_category_price', table_name='products')
    op.drop_index('ix_orders_user_status_created', table_name='orders')
    # ### end Alembic commands ###
