"""auto: category/product model changes

Revision ID: e3946014ab0b
Revises: 9d1b3f2a4c7e
Create Date: 2026-04-21 20:18:42.050766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3946014ab0b'
down_revision: Union[str, Sequence[str], None] = '9d1b3f2a4c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """No-op upgrade: archived original migration moved to alembic/archived.

    The original autogenerated migration attempted to change primary key types
    (VARCHAR -> INTEGER) which is incompatible with the current database data
    (UUID strings). We keep a copy in alembic/archived and leave this revision
    as a no-op so the repository can be advanced safely. Generate a fresh
    migration after this revision is applied.
    """
    pass


def downgrade() -> None:
    """No-op downgrade."""
    pass
