import { Link, NavLink, useNavigate } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertCircle, ArrowRight, Check, Minus, Plus, ShoppingBag, Trash2, X } from 'lucide-react'
import { api, authStore, endpoints, message, money, type Cart } from './lib'

export function Toasts() { const toasts = authStore((s) => s.toasts); return <div className="toast-stack">{toasts.map((t) => <div className={`toast ${t.type}`} key={t.id}>{t.type === 'error' ? <AlertCircle size={16} /> : <Check size={16} />}{t.message}</div>)}</div> }
export function Status({ value }: { value: string }) { return <span className={`status ${value.toLowerCase()}`}>{value.replace('_', ' ')}</span> }
export function Header() { const user = authStore((s) => s.user), toggle = authStore((s) => s.toggleCart); const nav = useNavigate(); const logout = async () => { try { await api.post('/auth/logout'); } finally { authStore.getState().clear(); nav('/') } }; return <header className="topbar"><Link className="brand" to="/"><span>α</span> ALPHA<span className="dim">/COMMERCE</span></Link><nav><NavLink to="/shop">Shop</NavLink><NavLink to="/orders">Orders</NavLink>{user?.is_admin && <NavLink className="admin-nav" to="/admin">Admin systems</NavLink>}</nav><div className="nav-actions">{user ? <><Link className="user-chip" to="/account">{user.username.slice(0, 1).toUpperCase()}</Link><button className="text-btn" onClick={logout}>Sign out</button></> : <Link className="text-btn" to="/login">Sign in</Link>}<button className="cart-button" onClick={toggle}><ShoppingBag size={18} /><span>Cart</span></button></div></header> }
export function Footer() { return <footer className="site-footer"><div className="footer-grid"><div className="footer-brand"><Link className="brand" to="/"><span>α</span> ALPHA<span className="dim">/COMMERCE</span></Link><p>High-performance asynchronous e-commerce platform &amp; inventory ledger.</p></div><div><h2>Platform</h2><Link to="/shop">Shop Catalog</Link><Link to="/orders">Order Tracking</Link><Link to="/contact">Developer APIs</Link><Link to="/">System Status</Link></div><div><h2>Company</h2><Link to="/contact">About Us</Link><a href="mailto:connect@alpha-commerce.tech">Contact Support</a></div><div><h2>Legal</h2><Link to="/privacy">Privacy Policy</Link><Link to="/terms">Terms of Service</Link><Link to="/contact">Security</Link></div></div><div className="footer-bottom"><span>© 2026 Alpha-Commerce Inc. All rights reserved.</span><a href="mailto:connect@alpha-commerce.tech">Support: connect@alpha-commerce.tech</a></div></footer> }
export function Skeleton({ rows = 6 }: { rows?: number }) { return <div className="skeleton-wrap">{Array.from({ length: rows }).map((_, i) => <div className="skeleton" key={i} />)}</div> }
export function CartDrawer() { const open = authStore((s) => s.cartOpen), toggle = authStore((s) => s.toggleCart), qc = useQueryClient(), toast = authStore((s) => s.toast); const { data: cart, isLoading } = useQuery({ queryKey: ['cart'], queryFn: endpoints.cart, enabled: open }); const mutate = useMutation({ mutationFn: ({ method, url, data }: any) => api({ method, url, data }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['cart'] }); toast('Cart updated.') }, onError: (e) => toast(message(e), 'error') }); if (!open) return null; const c = cart as Cart | undefined; return <><div className="scrim" onClick={toggle} /><aside className="cart-drawer"><div className="drawer-head"><div><small>YOUR SESSION CART</small><h2>Cart ledger</h2></div><button className="icon-btn" onClick={toggle}><X /></button></div>{isLoading ? <Skeleton rows={4} /> : !c?.items.length ? <div className="empty">Your cart is ready when you are.<br /><Link to="/shop" onClick={toggle}>Browse the catalog <ArrowRight size={15} /></Link></div> : <><div className="cart-items">{c.items.map((i) => <div className="cart-row" key={i.id}><div><b>{i.product.name}</b><code>{money(i.product.price)}</code></div><div className="quantity"><button onClick={() => mutate.mutate({ method: 'patch', url: `/api/v1/cart/items/${i.id}/decrease` })}><Minus size={13} /></button><span>{i.quantity}</span><button onClick={() => mutate.mutate({ method: 'put', url: `/api/v1/cart/items/${i.id}`, data: { quantity: i.quantity + 1 } })}><Plus size={13} /></button></div><button className="delete" onClick={() => mutate.mutate({ method: 'delete', url: `/api/v1/cart/items/${i.id}` })}><Trash2 size={15} /></button></div>)}</div><Coupon cart={c} /><div className="totals"><span>Subtotal <code>{money(c.total_price + (c.discount_amount || 0))}</code></span>{c.discount_amount > 0 && <span className="discount">Coupon · {c.coupon_code} <code>−{money(c.discount_amount)}</code></span>}<strong>Final total <code>{money(c.total_after_discount || c.total_price)}</code></strong></div><Link className="primary full" onClick={toggle} to="/checkout">Secure checkout <ArrowRight size={16} /></Link><button className="clear-cart" onClick={() => mutate.mutate({ method: 'delete', url: '/api/v1/cart/' })}>Clear cart</button></>}</aside></> }
function Coupon({ cart }: { cart: Cart }) { const qc = useQueryClient(), toast = authStore((s) => s.toast); const mutation = useMutation({ mutationFn: (code?: string) => code ? api.post('/api/v1/cart/apply-coupon', { code }) : api.delete('/api/v1/cart/remove-coupon'), onSuccess: () => { qc.invalidateQueries({ queryKey: ['cart'] }); toast('Coupon updated.') }, onError: (e) => toast(message(e), 'error') }); const submit = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); mutation.mutate(String(new FormData(e.currentTarget).get('code'))) }; return cart.coupon_code ? <button className="coupon-applied" onClick={() => mutation.mutate(undefined)}>{cart.coupon_code} applied <X size={14} /></button> : <form onSubmit={submit} className="coupon"><input name="code" placeholder="PROMO CODE" required /><button>Apply</button></form> }
